# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g serverless
    - run: serverless config credentials --provider aws --key ${{ secrets.GITHUB_TOKEN.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.GITHUB_TOKEN.AWS_SECRET_ACCESS_KEY }} --overwrite
    # - run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: npm ci
    - name: Deploy lambda function
      run: serverless deploy

        # env: 
        # AWS_ACCESS_KEY_ID: 
        # AWS_SECRET_ACCESS_KEY: 
   
